project_id = "eqxiapntfxfpmolvdknp"

[functions.generate-achievement-descriptions]
verify_jwt = false

[functions.chat]
verify_jwt = false

[functions.analyze-job-keywords]
verify_jwt = false

[functions.generate-cover-letter]
verify_jwt = false

[functions.format-gupy-experiences]
verify_jwt = false

[functions.generate-interview-scripts]
verify_jwt = false

[functions.generate-linkedin-content]
verify_jwt = false

[functions.format-learning-path]
verify_jwt = false

[functions.generate-about-me]
verify_jwt = false

[functions.generate-ats-cv]
verify_jwt = false
