project_id = "eqxiapntfxfpmolvdknp"

[functions.chat]
verify_jwt = false

[functions.analyze-job-keywords]
verify_jwt = false

[functions.generate-cover-letter]
verify_jwt = false

[functions.format-gupy-experiences]
verify_jwt = false
